pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // SCM se code download karne ke liye
                checkout scm
            }
        }

        stage('Build') {
            steps {
                // Windows par Docker build chalane ke liye 'bat' ka use kiya gaya hai
                bat "docker build -t flask-app:%BUILD_NUMBER% ."
            }
        }

        stage('Test') {
            steps {
                // Windows terminal par message print karne ke liye
                bat 'echo "Running basic tests..."'
            }
        }

        stage('Deploy to Staging') {
            when {
                branch 'develop'
            }
            steps {
                bat 'echo "Deploying to staging environment"'
            }
        }
    }

    post {
        success {
            echo 'Pipeline executed successfully'
        }
        failure {
            echo 'Pipeline failed'
        }
    }
}
